# User names
# Make directories in settings.STATIC_ROOT/datasets folder with the same names
user_list: ['Carlos', 'Georges', 'Father_Joseph', 'CarlosAI', 'GeorgesAI', 'Akram', 'Mehreen']
# for tags
tag_dictionary: { 'Region_paragraph': 'rgba(128, 28, 255, 0.1)', 
                  'Region_heading': 'rgba(128, 28, 255, 0.1)', 
                  'Region_logo': 'rgba(128, 28, 255, 0.1)',
                  'Region_letterhead': 'rgba(128, 28, 255, 0.1)',
                  'Region_floating': 'rgba(128, 28, 255, 0.1)',
                  'Region_pageNo': 'rgba(128, 28, 255, 0.1)',
                  'Region_signature': 'rgba(255, 255, 0, 0.1)', 
                  'Region_graphic': 'rgba(255, 255, 0, 0.1)',
                  'Region_decoration': 'rgba(255, 255, 255, 0.1)', 
                  'Region_noise': 'rgba(255, 255, 255, 0.1)',
                  'Region_separator': 'rgba(255, 255, 255, 0.1)',
                  'Region_linedrawing': 'rgba(255, 255, 255, 0.1)',
                  'Region_stamp': 'rgba(255, 255, 255, 0.1)',
                  'Archivist_Tag': 'rgba(255, 0, 255, 0.1)', 
                  'Crossed_out': 'rgba(255, 0, 255, 0.1)', 
                  'Printed_Regular': 'rgba(255, 28, 128, 0.1)', 
                  'Printed_Italics': 'rgba(28, 28, 255, 0.1)', 
                  'Printed_Bold': 'rgba(128, 200, 28, 0.1)', 
                  'Orient_top_bottom': 'rgba(128, 200, 28, 0.1)', 
                  'Orient_bottom_top': 'rgba(128, 200, 28, 0.1)'
                } 
